version: '3.8'

services:
  mongo:
    image: mongo:4.4.24-focal
    container_name: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - blog-net

  backend:
    build:
      context: ./backend
    image: rishabhraj7/blog-backend
    container_name: backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=${MONGO_URI}
    depends_on:
      - mongo
    networks:
      - blog-net

  frontend:
    build:
      context: ./frontend
    image: rishabhraj7/blog-frontend
    container_name: frontend
    restart: unless-stopped
    ports:
      - "3005:3005"
    depends_on:
      - backend
    networks:
      - blog-net

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - blog-net

volumes:
  mongo-data:

networks:
  blog-net:
    driver: bridge
