version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    image: rishabhraj7/blog-backend
    container_name: backend
    build:
      context: ./backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://localhost:27017/blog
    depends_on:
      - mongo

  frontend:
    image: rishabhraj7/blog-frontend
    container_name: frontend
    build:
      context: ./frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mongo-data: